CREATE TABLE RENTER (
    R_ID NUMBER(12,0) PRIMARY KEY NOT NULL,
    FIRST_NAME VARCHAR(128) NOT NULL,
    MIDDLE_INIT VARCHAR(12),
    LAST_NAME VARCHAR(128) NOT NULL,
    ADDRESS VARCHAR(1024) NOT NULL,
    CITY VARCHAR(128) NOT NULL,
    STATE VARCHAR(2) NOT NULL,
    POSTAL_CODE NUMBER(12, 0) NOT NULL
);

CREATE TABLE PROPERTY (
    LOC_NO NUMBER(12,0) PRIMARY KEY NOT NULL,
    LOC_NAME VARCHAR(128) NOT NULL,
    ADDRESS VARCHAR(1024) NOT NULL,
    CITY VARCHAR(128) NOT NULL,
    STATE VARCHAR(2) NOT NULL,
    POSTAL_CODE NUMBER(12,0) NOT NULL,
    UNIT_NO NUMBER(6,0) NOT NULL,
    FLR_SQ_FT NUMBER(6,2) NOT NULL,
    BDRM_COUNT NUMBER(6,0) NOT NULL,
    BTRM_COUNT NUMBER(6,0) NOT NULL,
    MAX_OCCUP NUMBER(6,0) NOT NULL,
    BASE_WK_RATE NUMBER(12,2) NOT NULL
);

CREATE TABLE AGREEMENT (
    R_ID NUMBER(12,0) PRIMARY KEY NOT NULL,
    FIRST_NAME VARCHAR(128) NOT NULL,
    MIDDLE_INIT VARCHAR(12),
    LAST_NAME VARCHAR(128) NOT NULL,
    ADDRESS VARCHAR(1024) NOT NULL,
    CITY VARCHAR(128) NOT NULL,
    STATE VARCHAR(2) NOT NULL,
    POSTAL_CODE NUMBER(12, 0) NOT NULL,
    TEL_NO NUMBER(12,0) NOT NULL,
    START_DATE DATETIME,
    END_DATE DATETIME,
    BASE_WK_RATE NUMBER(12,2) NOT NULL
);